security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /

            logout:
                path: /deconnexion
                target: /

        secured_area:
            form_login:
                csrf_token_generator: security.csrf.token_manager

    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }